name: Release Executables (with Cross)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: # 允许手动运行（但手动运行时不会创建 Release）

permissions:
  contents: write # 必须有写入权限

jobs:
  build_and_release:
    name: Build ${{ matrix.os_label }} (${{ matrix.arch_label }})
    runs-on: ${{ matrix.runner_os }}
    strategy:
      matrix:
        include:
          # Linux (通用)
          - runner_os: ubuntu-latest
            rust_target: x86_64-unknown-linux-musl # 推荐使用 musl 实现静态链接
            os_label: Linux
            arch_label: x64
            archive_ext: tar.gz
            exe_suffix: ""
            use_cross: true # <--- 标记为 true，表示使用 cross

          # macOS (Intel)
          - runner_os: macos-latest
            rust_target: x86_64-apple-darwin
            os_label: macOS
            arch_label: x64
            archive_ext: tar.gz
            exe_suffix: ""
            use_cross: false # <--- macOS 原生编译不需要 cross

          # macOS (Apple Silicon M1/M2)
          - runner_os: macos-latest
            rust_target: aarch64-apple-darwin
            os_label: macOS
            arch_label: arm64
            archive_ext: tar.gz
            exe_suffix: ""
            use_cross: false # <--- macOS 原生编译不需要 cross

          # Windows
          - runner_os: windows-latest
            rust_target: x86_64-pc-windows-msvc
            os_label: Windows
            arch_label: x64
            archive_ext: zip
            exe_suffix: ".exe"
            use_cross: true # <--- 标记为 true，表示使用 cross

    steps:
      - uses: actions/checkout@v4

      # 条件安装 Rust 工具链：原生平台直接安装，交叉编译平台不在这里安装
      - name: Install Rust toolchain (for native targets)
        if: ${{ !matrix.use_cross }}
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.rust_target }}

      # 条件安装 Cross：仅在需要交叉编译时安装
      - name: Install Cross (for cross targets)
        if: ${{ matrix.use_cross }}
        run: cargo install cross --git https://github.com/cross-rs/cross --tag v0.2.5 # 安装 cross 工具

      - name: Build Release Binary
        run: |
          if [[ "${{ matrix.use_cross }}" == "true" ]]; then
            # 如果使用 cross，需要提供目标
            cross build --release --target ${{ matrix.rust_target }}
          else
            # 否则使用 cargo
            cargo build --release --target ${{ matrix.rust_target }}
          fi
        # 如果你的项目有 C 依赖，例如 OpenSSL，可能需要以下环境变量
        # env:
        #   RUSTFLAGS: -C target-feature=+crt-static # 对于 musl libc 静态链接可能需要
        #   # PKG_CONFIG_ALLOW_CROSS: 1 # 某些 C 依赖可能需要
        #   # OPENSSL_STATIC: 1 # 如果你的项目依赖 OpenSSL 且需要静态链接

      - name: Package Artifact
        id: package_artifact
        shell: bash
        run: |
          APP_NAME=$(basename $(pwd))
          RELEASE_VERSION=${GITHUB_REF_NAME}
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          fi

          ARTIFACT_DIR="${APP_NAME}-${RELEASE_VERSION}-${{ matrix.os_label }}-${{ matrix.arch_label }}"
          mkdir -p "$ARTIFACT_DIR"

          cp target/${{ matrix.rust_target }}/release/${APP_NAME}${{ matrix.exe_suffix }} "$ARTIFACT_DIR/"
          cp README.md "$ARTIFACT_DIR/" || true
          cp LICENSE "$ARTIFACT_DIR/" || true

          ARCHIVE_NAME="${ARTIFACT_DIR}.${{ matrix.archive_ext }}"
          if [[ "${{ matrix.archive_ext }}" == "zip" ]]; then
            zip -r "$ARCHIVE_NAME" "$ARTIFACT_DIR"
          else
            tar -czvf "$ARCHIVE_NAME" "$ARTIFACT_DIR"
          fi
          echo "ASSET_PATH=$ARCHIVE_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release (only on tag push)
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          generate_release_notes: true

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/') && steps.create_release.outputs.upload_url
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ASSET_PATH }}
          asset_name: ${{ env.ASSET_PATH }}
